96.130% - fix: recent pypy3.9 now omits lines after jumps
We were seeing these failures in the nightly builds:

```
FAILED tests/test_arcs.py::LoopArcTest::test_continue - AssertionError:
  Possible arcs differ: minus is expected, plus is actual
    (-1, 1) # .1
    (1, 2) # 12
    (1, 5) # 15
    (2, 3) # 23
    (3, 1) # 31
  - (4, 1) # 41
    (5, -1) # 5.

  Missing arcs differ: minus is expected, plus is actual
  - (4, 1) # 41
  +

assert False
FAILED tests/test_arcs.py::LoopArcTest::test_break - AssertionError:
  Possible arcs differ: minus is expected, plus is actual
    (-1, 1) # .1
    (1, 2) # 12
    (1, 5) # 15
    (2, 3) # 23
    (3, 5) # 35
  - (4, 1) # 41
    (5, -1) # 5.

  Missing arcs differ: minus is expected, plus is actual
    (1, 5) # 15
  - (4, 1) # 41

assert False
FAILED tests/test_arcs.py::ExceptionArcTest::test_raise_followed_by_statement - AssertionError:
  Possible arcs differ: minus is expected, plus is actual
    (-1, 1) # .1
    (1, 2) # 12
    (2, 3) # 23
    (3, 4) # 34
    (4, 6) # 46
  - (5, 8) # 58
    (6, 7) # 67
    (7, 8) # 78
    (8, -1) # 8.

  Missing arcs differ: minus is expected, plus is actual
  - (5, 8) # 58
  +

assert False
FAILED tests/test_coverage.py::SimpleStatementTest::test_raise_followed_by_statement - AssertionError: [1, 2, 4, 5] != [1, 2, 3, 4, 5]
assert [1, 2, 4, 5] == [1, 2, 3, 4, 5]
  At index 2 diff: 4 != 3
  Right contains one more item: 5
  Full diff:
  - [1, 2, 3, 4, 5]
  ?        ---
  + [1, 2, 4, 5]
FAILED tests/test_coverage.py::SimpleStatementTest::test_break - AssertionError: [1, 2, 3, 5] != [1, 2, 3, 4, 5]
assert [1, 2, 3, 5] == [1, 2, 3, 4, 5]
  At index 3 diff: 5 != 4
  Right contains one more item: 5
  Full diff:
  - [1, 2, 3, 4, 5]
  ?           ---
  + [1, 2, 3, 5]
FAILED tests/test_coverage.py::SimpleStatementTest::test_continue - AssertionError: [1, 2, 3, 5] != [1, 2, 3, 4, 5]
assert [1, 2, 3, 5] == [1, 2, 3, 4, 5]
  At index 3 diff: 5 != 4
  Right contains one more item: 5
  Full diff:
  - [1, 2, 3, 4, 5]
  ?           ---
  + [1, 2, 3, 5]
```

https://nedbat.github.io/coverage-reports/reports/20230312_8eb95b5ad2/htmlcov
8eb95b5ad2: master